### ISSUE TITLE
Need

### ISSUE THREAD

**Issue by tw-e** [pengelana/blocklist#1]
@pengelana

Hi,
Can you add e-mail contact information on your website?

**Comment by pengelana** [comment]
You can contact via twitter dm, there’s link at the bottom.

**Comment by ariqmuhammadt** [comment]
I can't find your twitter dm, please provide another contact info. I need to discuss something with your DoH.
Thanks

**Comment by pengelana** [comment]
you can discuss here or open issue if you have problem with tiarap doh.

**Comment by 3xploiton3** [comment]
please build telegram group for flexible discuss
Very liked 👍
