### ISSUE TITLE
Accept connections through Port 853 (UDP) for DoQ

### ISSUE THREAD

**Issue by TheSkyLookingGood** [pengelana/blocklist#107]
Based on  [RFC 9250](https://www.rfc-editor.org/rfc/rfc9250.html) (DNS over Dedicated QUIC Connections)

> a DNS server that supports DoQ **MUST** listen for and accept QUIC connections on the dedicated UDP port 853 ([Section 8](https://www.rfc-editor.org/rfc/rfc9250.html#iana-considerations))

**Comment by pengelana** [comment]
not implemented yet.

**Comment by TheSkyLookingGood** [comment]
> not implemented yet.

What do you mean?

**Comment by pengelana** [comment]
dns-over-quic listen on udp/853:

`sdns://BAMAAAAAAAAAEjE3NC4xMzguMjkuMTc1Ojg1MwAMZG9oLnRpYXIuYXBw`

dns-over-quic listen on udp/784

`sdns://BAMAAAAAAAAAEjE3NC4xMzguMjkuMTc1Ojc4NAAMZG9oLnRpYXIuYXBw`
