### ISSUE TITLE
dns quic ga work di adguardhome

### ISSUE THREAD

**Issue by Helperinhere** [pengelana/blocklist#110]
Sesuai title... Quic ga work di adguard home semenjak versi terbaru mereka v0.107.7 di mana quic udah keluar draft stage. Kalo saya coba di adguard android ini masih bisa jd kurang tau penyebabnya ga worknya,

**Comment by pengelana** [comment]
Silakan dicoba lagi, baru saja diupgrade sesuai standar [RFC9250](https://datatracker.ietf.org/doc/rfc9250/).
