### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by Zusyaku** [pengelana/blocklist#112]
bang settingan dns untuk android yg bener dot.tiar.app.atau doh.tiar.app

for dns setting in android where is correct dot tiar app or doh tiar app plz answer
![Screenshot_1](https://user-images.githubusercontent.com/71582475/176997213-908530cc-10d6-40ac-b742-2fea93d9e7aa.png)

**Comment by pengelana** [comment]
Keduanya bisa dipakai, doh.tiar.app atau dot.tiar.app.

**Comment by Zusyaku** [comment]
bagusan mana bang atau sama aja

**Comment by pengelana** [comment]
Server yg sama. `dot.tiar.app` adalah alias dari `doh.tiar.app`.
