### ISSUE TITLE
Beberapa Iklan Tembus

### ISSUE THREAD

**Issue by ardissaps** [pengelana/blocklist#113]
Om kalau ditest pakai ini kok ada beberapa masih tembus ya?
https://d3ward.github.io/toolz/adblock.html

**Comment by pengelana** [comment]
Karena yg diblok Tiarap bukan domain, tetapi subdomain.
Misalnya `doubleclick.net` tidak diblok tetapi yg diblok `googleads4.g.doubleclick.net`, `fls.doubleclick.net` dsb.

Contoh lainnya `googleadservices.com` tidak diblok tapi yg diblok `partner.googleadservices.com` dan `4.afs.googleadservices.com` dst.

**Comment by ardissaps** [comment]
ok thanks infornya om
