### ISSUE TITLE
Block This Domain

### ISSUE THREAD

**Issue by BangKuntet** [pengelana/blocklist#116]
http://lamanlabuh.aduankonten.id/

bang kalo block itu situs gimana wkwkwkwk
pake dns lu tapi sering masuk situ apa yg salah ya

**Comment by pengelana** [comment]
Yang salah hpnya, berarti tidak terknoneksi ke Tiarap.
Coba restart hpnya. Lalu test ke [dnsleaktest.com](https://dnsleaktest.com/).

Hasilnya seperti ini:

![image](https://user-images.githubusercontent.com/787301/181808454-9a7f6d3d-869c-4b1e-a85b-42b39fd2f1b4.png)

**Comment by BangKuntet** [comment]
ternyata browser sendiri yg pake dns lain dari pengaturanya terus dimatikan dan bisa gan
resolver tiar app gitu siangpore
