### ISSUE TITLE
Diblokir ISP

### ISSUE THREAD

**Issue by akn19** [pengelana/blocklist#118]
Apa dns ini tidak bisa membuka web yang di blokir isp? Saya coba buka reddit tetap nggak bisa. 

![Screenshot_2022-08-03-19-42-31-170_com android settings](https://user-images.githubusercontent.com/86169232/182610903-4b1a5f97-d564-45b2-ac31-fcdade7d365d.jpg)
.
![Screenshot_2022-08-03-19-40-30-626_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/86169232/182610872-e3d082f5-92ef-40e0-b638-4c3cfe7564fd.jpg)
![Screenshot_2022-08-03-19-42-15-562_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/86169232/182610888-c56db2b6-c35b-4ede-a3e8-89511674a834.jpg)

**Comment by akn19** [comment]
Device : POCO F4 Miui 13 (android 12)

**Comment by akn19** [comment]
ISP : XL

**Comment by pengelana** [comment]
DNS ini bukan buat membuka blokir ISP.
Silakan baca disini: https://github.com/pengelana/blocklist/wiki/FAQ

**Comment by 20excal07** [comment]
kalo sedang di jaringan mobile, penyedia jasa telco kita semua sudah menggunakan DPI (Deep Packet Inspection) untuk memblok akses ke website, dan tidak bisa dihindari dgn sekedar menggunakan private/encrypted DNS. Untuk itu, perlu menggunakan sesuatu seperti PowerTunnel, atau dengan menyalakan aplikasi VPN biasa.

**Comment by pengelana** [comment]
Banyak yg bilang _penyedia jasa telco menggunakan DPI_, tapi dari semua yg bilang _penyedia jasa telco menggukan DPI_ **tidak ada seorang pun bisa membuktikan secara teknikal** bahwa _penyedia jasa telco menggunakan DPI._ Kalau ada yg bisa membuktikan _penyedia jasa telco menggunakan DPI_, tolong di post kesini, sangat tertarik untuk melihat.

**Comment by lantip** [comment]
![telkomsel-proven-dpi-test](https://user-images.githubusercontent.com/3334064/183255308-f7167f83-c330-4994-bd9a-6e14cd291046.jpg)

Ini capture tcp untuk telkomsel. Sepertinya memang, paling tidak di Telkomsel, terdeteksi menggunakan DPI.

**Comment by pengelana** [comment]
Terima kasih, Pak @lantip. Anda adalah orang pertama yang tidak asbun.

**Comment by 20excal07** [comment]
![image](https://user-images.githubusercontent.com/12115769/183260326-88322963-78a6-49d3-a7b7-b5250581fecd.png)

Can confirm juga buat 3 (Tri).

**Comment by pengelana** [comment]
Thanks @20excal07, ini akses dari daerah mana?

**Comment by 20excal07** [comment]
Jakarta :p
