### ISSUE TITLE
Request rule filter adblock

### ISSUE THREAD

**Issue by 3xploiton3** [pengelana/blocklist#12]
Gan kalau bisa minta tolong buatkan rule filter untuk adblock bisa tidak?

Domain di convert ke rule adblock
Seperti contoh dibawah ini
Fungsi buat deteksi tracker menggunakan adguard

||kaffnet.com^

![](https://i.imgur.com/UjPT5VB.jpg)

**Comment by cebolang** [comment]
![dohtiarapp](https://user-images.githubusercontent.com/49541575/65483455-6b80ba00-dec6-11e9-8ebc-71a92afd97db.jpeg)

Bukannya jika kita arahkan DNS servernya ke doh.tiar.app, bisa kita ambil manfaat dari keduanya?
Tapi untuk saya, semua filter adguard malah sengaja saya nonaktifkan, btw lebih sering pakai DNSCloak daripada AdGuard saat mobile.

**Comment by pengelana** [comment]
Buat testing ya? 

Sebenernya kalau pakai tiarap di adguard kalau diblok domainnya berwarna merah (adguard pro) atau pink (adguard) atau check kalau server return 127.0.0.1 buat A record (ipv4), ::1 buat AAAA record (ipv6)

**Comment by 3xploiton3** [comment]
@pengelana ada contoh atau gambar?
Maaf saya masih awam,

Bila saya aktifkan dnscrypt di adguard android, tdk terdeteksi bahwa domain itu terblock atau tidaknya oleh tiar.app

**Comment by pengelana** [comment]
## Adguard premium di ios:

![image](https://user-images.githubusercontent.com/787301/65519951-68fb8000-df19-11e9-91b4-1240d4b7c0ef.png)


## DNS request details 

![image](https://user-images.githubusercontent.com/787301/65520516-45850500-df1a-11e9-99a6-9ea7ddebe2f7.png)

**Comment by 3xploiton3** [comment]
![](https://i.imgur.com/8BM5NVi.jpg)
 ![](https://i.imgur.com/GLDd7qe.jpg)

Saya pakai adguard pro,
Hanya ada filtering log


Tampilan seperti diatas, malahan tertulis processed bukan blocked

**Comment by pengelana** [comment]
Adguard di Android ya? setting DNS-nya gimana?

**Comment by 3xploiton3** [comment]
Saya setting filter semua nonaktifkan,
Saya pakai tiar.app dnscrypt,
Kok malah seperti dns biasa filtering dr tiar ke bypass

![](https://i.imgur.com/yd34rOK.jpg)
![](https://i.imgur.com/xd14XoK.jpg)
![](https://i.imgur.com/klEf4Pj.jpg)
![](https://i.imgur.com/x46pgG0.jpg)
![](https://i.imgur.com/Ups119U.jpg)

**Comment by pengelana** [comment]
Coba ke `https://www.dnsleaktest.com/` lalu pilih `Extended test`, hasilnya ke DNS server mana.

**Comment by 3xploiton3** [comment]
Settingan saya seperti ini
![](https://i.imgur.com/owT6eRm.jpg)
![](https://i.imgur.com/Wr5ZdhP.jpg)
![](https://i.imgur.com/jkxL5tH.jpg)

Kenapa malah ke google ya? :flushed:
Saya buka reddit.com biasanya ke block, ini terbuka

**Comment by pengelana** [comment]
Di Android-nya ada settingan PrivateDNS/DNS Pribadi? Coba OFF-kan.

**Comment by 3xploiton3** [comment]
Ya saya matikan, berhasil ke dns tiar,
Tetapi ads tetap muncul, settingan tdk ada yg dirubah dr sebelumnya

![](https://i.imgur.com/gpV0Bq7.jpg)
![](https://i.imgur.com/5V1zVpe.jpg)
![](https://i.imgur.com/EA6Osu9.jpg)

**Comment by 3xploiton3** [comment]
Ok berhasil ke dns tiar,
Hanya beberapa kali saya coba tetap dialihkan ke google walu private dns sdh dimatikan,
Setelah di reclick dns di adguard baru berhasil

**Comment by pengelana** [comment]
Sudah berhasil liat domain yg diblok?

**Comment by 3xploiton3** [comment]
@pengelana belum, ini yang masih jadi masalah,
Apa ada cara lain?
Saya pakai android

**Comment by pengelana** [comment]
Hasil dari `https://www.dnsleaktest.com/` bagaimana?

**Comment by 3xploiton3** [comment]
> 
> 
> Hasil dari `https://www.dnsleaktest.com/` bagaimana?

berhasil ke tiar.app
[screenshot](https://camo.githubusercontent.com/82c35c4849f424b071c4d5f63ab51690111517b0/68747470733a2f2f692e696d6775722e636f6d2f4b5863315632512e6a7067)

**Comment by pengelana** [comment]
log dns query kelihatan?

**Comment by 3xploiton3** [comment]
@pengelana maksudnya? Sdh saya sertakan link screenshot

**Comment by pengelana** [comment]
dari log dns sudah bisa kelihatan domain yg diblok?

**Comment by 3xploiton3** [comment]
Itulah pertanyaan kenapa saya bikin thread ini,

Bagaimana cara lihat log dns di android?

**Comment by cebolang** [comment]
Ini di iOS aplikasi AdGuard baik2 saja, atau mungkin perlu dicoba versi stabil, bukan nightly. Oya, lebih tepat jika pertanyaan ditujukan ke developer AdGuardnya, karena DNS servernya tidak bermasalah. Berikut link official adguard telegram grup t.me/adguard_en
![IMG_6309](https://user-images.githubusercontent.com/49541575/65943684-4528c480-e45a-11e9-9cad-d32db32a4b2c.png)
![IMG_6310](https://user-images.githubusercontent.com/49541575/65943685-4528c480-e45a-11e9-8411-89493f74d142.jpg)

**Comment by 3xploiton3** [comment]
Sudah saya ganti ke versi adguard release stable, menu dns request log tidak ada

![](https://i.imgur.com/re281Ck.jpg)
![](https://i.imgur.com/xF4aglS.jpg)

**Comment by pengelana** [comment]
Adguardnya download dari Playstore atau dari web Adguard langsung?

**Comment by pengelana** [comment]
Dari filter log coba dicheck, A record hasilnya 127.0.0.1 atau AAAA hasilnya ::1

![image](https://user-images.githubusercontent.com/787301/66013001-1fec9280-e4fc-11e9-9389-de2a5eabe288.png)
