### ISSUE TITLE
Does this dns support "Query Padding"?

### ISSUE THREAD

**Issue by enjoe842** [pengelana/blocklist#120]
Does this dns support "Query Padding"?

I want to use DNSCrypt using YogaDNS client, but in DNSCrypt settings there is an option to enable or disable query padding.

in the YogaDNS documentation, it is explained that
"For the DNSCrypt protocol, you can specify the Public key and Provider name (both parameters are mandatory) as seen below. Disable query padding should be set if the server does not properly support this feature."

Thanks before.

![qwd](https://user-images.githubusercontent.com/33560815/183546330-cac6f1a4-b3f0-46b6-94b1-beda4cc0b3b2.png)

**Comment by pengelana** [comment]
Padding supported.
