### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by BangKuntet** [pengelana/blocklist#121]
gan apa dns ini ngeblock iklan dan bisa bypas situs yg diblokir

**Comment by akn19** [comment]
https://github.com/pengelana/blocklist/wiki/FAQ#3-apakah-tiarap-ngeblok-iklan

**Comment by akn19** [comment]
https://github.com/pengelana/blocklist/wiki/FAQ#12-apakah-tujuan-tiarap-buat-bypass-blokir-kominfo

**Comment by pengelana** [comment]
Sudah dijawab di [118](https://github.com/pengelana/blocklist/issues/118)
