### ISSUE TITLE
source & server

### ISSUE THREAD

**Issue by wigas-angga** [pengelana/blocklist#122]
@pengelana 
- base source nya darimana? bisa di-publish kah?
- memang tidak ada server di jakarta/id ya?

**Comment by pengelana** [comment]
> @pengelana
> 
>     * base source nya darimana? bisa di-publish kah?

https://github.com/pengelana/blocklist/blob/master/domain.txt
https://github.com/pengelana/blocklist/blob/master/domain.rpz
> 
>     * memang tidak ada server di jakarta/id ya?

Tidak ada.

**Comment by wigas-angga** [comment]
itu yang sudah hasil kompilasi kan? maksudnya base source awalnya ambil darimana

**Comment by pengelana** [comment]
> itu yang sudah hasil kompilasi kan? maksudnya base source awalnya ambil darimana

Memangnya ada masalah dengan https://github.com/pengelana/blocklist/blob/master/domain.txt?
