### ISSUE TITLE
https://www.astrill.com/dns-leak-test

### ISSUE THREAD

**Issue by 3xploiton3** [pengelana/blocklist#13]
Saya cek dnsleak ada kebocoran, apakah ini dari aplikasi intra atau dari doh.tiar.app?
dnsleaktest.com versi extended msh aman, tetapi coba pakai astrill dns full scan ada yg mengarah ke google

![](https://i.imgur.com/RGQ4QQS.jpg)

**Comment by pengelana** [comment]
Di Androidnya ada settingan yg mengarah ke google dan doh.tiar.app
