### ISSUE TITLE
doh.tiar.app

### ISSUE THREAD

**Issue by Anon6662** [pengelana/blocklist#130]
Hiya
is doh.tiar.app online?

Pinging doh.tiar.app [174.138.29.175] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

[https://github.com/pengelana/blocklist/wiki/DNS-over-HTTPS-(DoH)](url)

**Comment by pengelana** [comment]
Yes, it is up. `https://status.tiarap.net/`
It will not respond to icmp echo request.

**Comment by Anon6662** [comment]
What 1's can be used as regular dns in windows?
need two dns ip's so regular dns are not auto generated by isp
