### ISSUE TITLE
Block Req [pasarbali-malls.com]

### ISSUE THREAD

**Issue by MagicalAlchemist** [pengelana/blocklist#139]
Link : 
https://pasarbali-malls.com

**Phising and scam site, confirmed by official store in facebook**
https://www.facebook.com/Pasarbali.id2020/posts/643605677772262?__cft__[0]=AZUh4H03TQ8VSS1_LFEp0rTo95IfZL388vskNRuBXWJaI9RsLRGJq5sVHWfdb0SJq3W-h_gaYwusBeY02P4IizLY3dgqwJbXjDP6tDxuAHnUipCzNaEaMX1iU8_6guaa32vofZB8K2d-JFvHGuYzAhA2aOcxX7KF1Dr-hIv-YTah2jcU9EEMVSYPb8mkkIDAAgZJNoHNo8dRMqPcHQQLJTcj&__tn__=%2CO%2CP-R

**Comment by pengelana** [comment]
Done, thanks!
