### ISSUE TITLE
Block Req [orami.cloud]

### ISSUE THREAD

**Issue by MagicalAlchemist** [pengelana/blocklist#140]
Link: 
https://orami.cloud/h5

**Fraud, confirmed by official store via website**
https://www.orami.co.id/magazine/hati-hati-terhadap-penipuan-yang-mengatasnamakan-orami

**Comment by MagicalAlchemist** [comment]
Another site:
https://orami.life/h5/

**Comment by pengelana** [comment]
Done, thanks!
