### ISSUE TITLE
Block req - Scam & Fraud List

### ISSUE THREAD

**Issue by MagicalAlchemist** [pengelana/blocklist#141]
**Fake Shop**
1. https://www.toko999.shop
2. https://toko999.net/
_Evidence :_ 
https://www.trustpilot.com/review/www.toko999.shop
https://www.facebook.com/groups/188766661163915/posts/8997694803604346/
https://www.facebook.com/groups/188766661163915/posts/8997836893590137/

3. https://akulaku.me
_Evidence :_ 
https://mediakonsumen.com/2023/01/16/surat-pembaca/penipuan-bisnis-online-mengatasnamakan-pt-akulaku-finance-akulaku-me

4. http://goshop.vin/
_Evidence :_ 
https://www.virustotal.com/gui/url/3bf1d9b3fb82c7a7a52d2947d2c86e0dabb51e330fcf5ea212ac6a298bf0ce2b
https://www.facebook.com/groups/188766661163915/posts/8597458213628009/

5. https://mmmjemp.cn/
6. https://bankruptcymelodious.cn/
7. https://qxowtod.cn/
8. https://crueltyspongy.cn/
9. https://ambulancesodium.cn/
10. https://negotiatefoam.cn/
11. https://deceptivebuffalo.cn/
_Evidence :_ **Confirmed by KAI**
https://www.kai.id/information/full_news/5521-kembali-marak-masyarakat-agar-waspada-penipuan-berkedok-promo-kai

**Comment by pengelana** [comment]
Done, Thank you.
