### ISSUE TITLE
Block Req #3

### ISSUE THREAD

**Issue by MagicalAlchemist** [pengelana/blocklist#143]
fms88.shop <- scam/fraud, confirmed.
evidence : 
https://www.facebook.com/groups/188766661163915/posts/8611943742179456/

oneparttimejob.com <- scam/fraud, suspected but most likely.
evidence : 
https://www.facebook.com/groups/826359317490446/posts/5052565721536430/

jne-express.my.id <- stealing personal information, confirmed.
evidence : 
https://twitter.com/silverboys_mate/status/1630762454597922817

**Comment by pengelana** [comment]
Done, thanks!
