### ISSUE TITLE
Block Req #4 Low rated review (indicated fraud)

### ISSUE THREAD

**Issue by MagicalAlchemist** [pengelana/blocklist#144]
1. importir.org
Evidence : https://www.kredibel.co.id/review/importir.org

2. orderonline.id
Evidence : https://www.kredibel.co.id/review/orderonline.id

3. infishta.com
Evidence : https://www.kredibel.co.id/review/infishta.com 

4. vestifarm.com
Evidence : https://www.kredibel.co.id/business/vestifarm.com

5. igrow.asia
Evidence : https://www.kredibel.co.id/business/igrow.asia

**Comment by pengelana** [comment]
Done, Thanks!
