### ISSUE TITLE
i am getting unbound error when trying DOT for unbound 

### ISSUE THREAD

**Issue by devmalick** [pengelana/blocklist#149]
Apr  1 10:01:26 | unbound | 88780 | [88780:3] notice: ssl handshake failed 174.138.29.175 port 853
-- | -- | -- | --
Apr  1 10:01:26 | unbound | 88780 | [88780:3] error: ssl handshake failed crypto error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name

**Comment by pengelana** [comment]
Add [tls-cert-bundle](https://nlnetlabs.nl/documentation/unbound/unbound.conf/) option on the server section.

~~~
server:
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"
~~~

and configure forward-zone as below:

~~~
 forward-zone:
   name: "."
   forward-first: yes
   forward-tls-upstream: yes
   forward-addr: 174.138.29.175@853#dot.tiar.app
~~~
