### ISSUE TITLE
Phising

### ISSUE THREAD

**Issue by cebolang** [pengelana/blocklist#15]
![788435B8-17E0-4595-A579-A5FB23213172](https://user-images.githubusercontent.com/49541575/66788085-74d2d480-ef10-11e9-8cf4-0cec3425608e.png)

https://amazon-authenticate-account.unparkerba-doom.business/ap/m.signin?openid.pape.max_auth_age=0be2d2e40046f3f85e7215cd954ae31d2f636327&locale=id_ID

**Comment by pengelana** [comment]
Done, Thanks!
