### ISSUE TITLE
DNS IPv4 on port 53 not available in EU?

### ISSUE THREAD

**Issue by thomasmerz** [pengelana/blocklist#150]
I can't ping both IPs or use DNS service on port 53 with Vodafone provider in germany and my Hetzner cloudservers in germany and finnland. I'm using
> DNS IPv4: 174.138.21.128 / 188.166.206.224 - port 53

Is your service only available for non-EU IPs? Some kind of geo-blocking? Or any other issues that I can't see or can't understand right now?

**Comment by PeterDaveHello** [comment]
I can verified that the issue exists not only in EU, but many other places also have the connectivity issue, used hundreds of public and private hosts from different locations, the failed ratio high significant high. Just EU failed 100%.

Is there anything we can help here?

**Comment by devmalick** [comment]
Should we stop using it

**Comment by pengelana** [comment]
I just came back from a trip.

The issue should resolved now, Linux tc filter was applied automatically to drop packet when there are too many tcp request to port 53/5003 to protect the system and only allow from SEA countries.

it doesn't affect other services such as DoT/DoH/DoQ etc.

sorry for the inconvenience.

**Comment by PeterDaveHello** [comment]
@pengelana thanks for the update! Just curious do you need to manually unblock those IP addresses? Still notice that the failed rate pretty high compared to any other public resolvers listed here: https://github.com/PeterDaveHello/chkdomain

**Comment by pengelana** [comment]
@PeterDaveHello, based on coutry prefix. Will you be able to test again? 
Let me know if the failed rate still high.
Thanks!

**Comment by PeterDaveHello** [comment]
@pengelana yes, if I randomly pick a few hundreds of location to run the test, the fail rate is about 83%, which means a lot of locations are blocked? Not sure if the threshold should be raised, or it might be an availability or reliability issue of a public DNS 🤔

**Comment by pengelana** [comment]
There is a mechanism to prevent abuse to the port 53/5003 (Do53), so it can gives more resources to DoH/DoH3/DoT/DoQ. I increased the threshold, can you help to test again? thank you.

**Comment by pengelana** [comment]
@PeterDaveHello, I increased the threshold again, can you help to test?

**Comment by PeterDaveHello** [comment]
Success rate about 80%~90% now 👍 BTW, maybe you can find that kind of information from iptables log?

**Comment by pengelana** [comment]
@PeterDaveHello I don't have/keep logs and I don't use iptables. It is the smallest droplet serving thousand of connection/queries every second.

**Comment by PeterDaveHello** [comment]
If the loading is acceptable, maybe the threshold can be increased still, BTW, DNS using TCP seems to failed much much higher than UDP here, just FYI.
