### ISSUE TITLE
Cannot resolve wifi.id login page

### ISSUE THREAD

**Issue by raffifu** [pengelana/blocklist#151]
I've a problem while trying to access wifi.id login page. From the screenshot below i'm trying to resolve `welcome2.wifi.id` with cloudflare, google and tiarap. All of the dns works but tiarap doesn't return anything

![image](https://github.com/pengelana/blocklist/assets/22138274/d9ae7ad7-ff4a-47c4-9738-8b9f2b33bdcf)

I found [this issue](https://github.com/pengelana/blocklist/issues/16). But, i think the problem still exist

**Comment by pengelana** [comment]
10.0.0.0/8 is Private IP range and to prevent [dns rebinding ](https://en.wikipedia.org/wiki/DNS_rebinding) the resolver will not return answer.

https://unit42.paloaltonetworks.com/dns-rebinding/
