### ISSUE TITLE
Tiarap not work anymore with adguardhome

### ISSUE THREAD

**Issue by Manssizz** [pengelana/blocklist#155]
hello. thanks for great work! \
i have a problem since a few week, tiarap cant use in adguardhome. i've tried `doh, dot, quic` but no one work combine with adguarhome. 

![image](https://github.com/pengelana/blocklist/assets/23637327/6058e4ab-4084-4faa-9bfe-38cdd123006c)

**Comment by pengelana** [comment]
What is your IP address?

**Comment by Manssizz** [comment]
![image](https://github.com/pengelana/blocklist/assets/23637327/026963b0-0028-4476-9dad-5891137adc34)
i put tiarap on openwrt router. do tiarap restrict ip address?

**Comment by pengelana** [comment]
Please, try again.

**Comment by Manssizz** [comment]
that's happen again

![image](https://github.com/pengelana/blocklist/assets/23637327/77fc4c6f-41e4-489e-ba38-227a6e13c92d)
