### ISSUE TITLE
Wifi.id login page

### ISSUE THREAD

**Issue by 3xploiton3** [pengelana/blocklist#16]
https://prntscr.com/prfeaw

Gak bisa masuk wifi.id

**Comment by cebolang** [comment]
![29DD9A2F-70FB-403B-8A8A-E542248D6650](https://user-images.githubusercontent.com/49541575/68069320-4454bc80-fd91-11e9-85e3-063b3664e76d.png)
Saya bisa tuh

**Comment by 3xploiton3** [comment]
Bukan web wifi.id tapi login page waktu mau konek wifi, cek screenshot saya disitu ada alamat yg terblok, sdh saya coba ganti ke dns lain seperti google atau isp bisa masuk, pakai tiar stuck di halamn itu

**Comment by pengelana** [comment]
Gak diblok, bisa resolve di tiarap:

~~~
$drill a connect.rom.miui.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 10541
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; connect.rom.miui.com.        IN      A

;; ANSWER SECTION:
connect.rom.miui.com.   38      IN      A       161.117.71.187

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 15 msec
;; SERVER: 10.11.12.8
;; WHEN: Sun Nov  3 17:56:24 2019
;; MSG SIZE  rcvd: 54
~~~

**Comment by 3xploiton3** [comment]
Kemarin Saya cek di wifi id lain hasil juga sama, ga bisa masuk login page

**Comment by pengelana** [comment]
Domain `connect.rom.miui.com` tidak ada di dalam db tiarap, yg block mungkin aplikasi lain di hp-nya.

**Comment by 3xploiton3** [comment]
Saya cek lagi ada beberapa ip yg terkait mungkin terblok

![](https://i.imgur.com/fxS3bmx.jpg) 
![](https://i.imgur.com/0TfQKnC.jpg)
![](https://i.imgur.com/qKUfgD3.jpg)

Saya test menggunakan adguard android semua filter saya hidupkan, pakai dnscrypt adguard dns, mode proxy bisa melewati wifi.id

Juga saya test pakai private dns google bs masuk,

Klo ini ip setelah masuk wifi.id
https://lp.wifi.id/?NG94RktRQ3drZ05SbEZqOW5yenZ1VHMxeTFtU3BXWHM0S0NHRUpmNHd0WWdLd1k0TGdsT1FKcXloVUVsQ1VUY3pTQk5VZVlxeTNDM0NWRHFRTnZ4bEhRQ2ttVmxwVUpKTUJKV0ZUbHJPZEZISkU5QlVyNGFSeDBnSDVGQXliNkVwbGsvTnF3dlNZdXJIWkV4WUVQdjl2MXlSRTNmaDF2QU5lMjZiWUs4SFVxRTRyZTFNMWxkdTFaRVd1WE11TFA4

**Comment by pengelana** [comment]
Tiarap, tidak ngeblok IP, cuma domain name.
