### ISSUE TITLE
Jarelllama's Scam Blocklist 

### ISSUE THREAD

**Issue by jarelllama** [pengelana/blocklist#163]
Hi! I'm the maintainer of https://github.com/jarelllama/Scam-Blocklist. I noticed you're using an outdated list of mine. If you're still keen in using my scam blocklist, here are the formats and links to them I currently offer:

| Format | Syntax |
| --- | --- |
| [Adblock Plus](https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/adblock/scams.txt) | \|\|scam.com^ |
| [Dnsmasq](https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/dnsmasq/scams.txt) | local=/scam.com/ |
| [Unbound](https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/unbound/scams.txt) | local-zone: "scam.com." always_nxdomain |
| [Wildcard Asterisk](https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/wildcard_asterisk/scams.txt) | \*.scam.com |
| [Wildcard Domains](https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/wildcard_domains/scams.txt) | scam.com |

The project has gone through major changes since the old list got decommissioned. If you'd like to read about the blocklist's updated mission, you can read more in the [README](https://github.com/jarelllama/Scam-Blocklist).

**Comment by pengelana** [comment]
Hi @jarelllama Thanks.
