### ISSUE TITLE
DNS dot.tiar.app di jam jam tertentu terkadang muncul pesan "Tidak dapat terhubung"

### ISSUE THREAD

**Issue by Reno-Sifana** [pengelana/blocklist#164]
Selamat malam @pengelana ini mau informasikan di jam jam tertentu kenapa ya akhir akhir ini terkadang DNS dot.tiar.app terkadang muncul pesan "Tidak dapat Terhubung" di hp Android beberapa hari ini (April 2024)? beberapa bulan yang lalu seingatku jarang gangguan DNS nya.

ini saya selalu nyalakan DNS Pribadi (dot.tiar.app) di hp Android buat blokir iklan juga

**Comment by freepr0xy** [comment]
> Selamat malam @pengelana ini mau informasikan di jam jam tertentu kenapa ya akhir akhir ini terkadang DNS dot.tiar.app terkadang muncul pesan "Tidak dapat Terhubung" di hp Android beberapa hari ini (April 2024)? beberapa bulan yang lalu seingatku jarang gangguan DNS nya.
> 
> ini saya selalu nyalakan DNS Pribadi (dot.tiar.app) di hp Android buat blokir iklan juga

Betul bang, ane juga mengalami hal yg sama. Pengguna yg tiap nyalain hp memastikan "tiarap" ane nyala ato kaga, setiap "no internet" dengan terpaksa mematikan fitur DOH di Intra ane, akhirnya sering ga pake lagi DOH karna kendala diatas

**Comment by Reno-Sifana** [comment]
> > Selamat malam @pengelana ini mau informasikan di jam jam tertentu kenapa ya akhir akhir ini terkadang DNS dot.tiar.app terkadang muncul pesan "Tidak dapat Terhubung" di hp Android beberapa hari ini (April 2024)? beberapa bulan yang lalu seingatku jarang gangguan DNS nya.
> > ini saya selalu nyalakan DNS Pribadi (dot.tiar.app) di hp Android buat blokir iklan juga
> 
> Betul bang, ane juga mengalami hal yg sama. Pengguna yg tiap nyalain hp memastikan "tiarap" ane nyala ato kaga, setiap "no internet" dengan terpaksa mematikan fitur DOH di Intra ane, akhirnya sering ga pake lagi DOH karna kendala diatas

iya hehe. waktu kejadian dah ngecek di laptop (pake Firefox pake DOH Cloudflare (bawaan Firefox) bisa akses web kok). langsung ane matikan bentar DNS nya.

**Comment by pengelana** [comment]
Hi @Reno-Sifana @freepr0xy Terima kasih atas infonya.
