### ISSUE TITLE
blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [pengelana/blocklist#166]
[i] Target: https://raw.githubusercontent.com/pengelana/blocklist/master/domain.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 1783159 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "com"

**Comment by pengelana** [comment]
Thank you.
