### ISSUE TITLE
whitelist tawk.to

### ISSUE THREAD

**Issue by rainazure** [pengelana/blocklist#17]
Terima kasih atas DOH yang bantu untuk ngurangi iklan saat browsing. 
namun saya tidak dapat akses tawk.to, yang saya gunakan sebagai free live chat di situs saya. 
mungkin bisa di-whitelist?

terima kasih. 

-sekalian nambah https://fd66f2cf284a6bb.com/ untuk di blacklist (iklan ini pernah muncul di situs yang saya selalu ikuti.. :p)

Terima kasih, lagi. :)

**Comment by pengelana** [comment]
Done, Thanks!
