### ISSUE TITLE
DNS Bocor

### ISSUE THREAD

**Issue by ryandhikacc** [pengelana/blocklist#176]
![image](https://github.com/user-attachments/assets/c33864cf-986f-4d65-8d73-bc18c82da983)
Izin tanya mas, ini saya pakai dnscrypt di windows kenapa DNS nya masih bocor ya? sebelumnya maaf gabisa pake opsi mudah secure dns di chrome karena chromenya managed by orgs saya..

**Comment by pengelana** [comment]
Konfigurasi di windows untuk dnscryptnya gimana?

**Comment by ryandhikacc** [comment]
sesuai tutorial di github dnscrypt mas, kalo di windowsnya sih set ke 127.0.0.1

**Comment by ryandhikacc** [comment]
![image](https://github.com/user-attachments/assets/69f227bb-4cc3-418e-86b9-481f478b5eb8)
sip thanks saran pake yogadns nya mas, skrg udah aman😁
