### ISSUE TITLE
whitelist: drugs.com

### ISSUE THREAD

**Issue by rickyson96** [pengelana/blocklist#178]
https://www.drugs.com/support/about.html
>Drugs.com is the largest, most widely visited, independent medicine information website available on the Internet. Our aim is to be the Internet’s most trusted resource for drug and related health information. We will achieve this aim by presenting independent, objective, comprehensive and up-to-date information in a clear and concise format for both consumers and healthcare professionals.

Thank you!

**Comment by pengelana** [comment]
Done, Thanks!
