### ISSUE TITLE
DoH flag in chrome/chromium on version 78 

### ISSUE THREAD

**Issue by compliment** [pengelana/blocklist#18]
It should be `--enable-features="DnsOverHttps<DoHTrial" --force-fieldtrials="DoHTrial/Group1" --force-fieldtrial-params="DoHTrial.Group1:Fallback/true/Templates/https%3A%2F%2Fdoh.tiarap.org%2Fdns-query"` now for https://doh.tiarap.org/dns-query

and `--enable-features="DnsOverHttps<DoHTrial" --force-fieldtrials="DoHTrial/Group1" --force-fieldtrial-params="DoHTrial.Group1:Fallback/true/Templates/https%3A%2F%2Fdoh.tiar.app%2Fdns-query"` for https://doh.tiar.app/dns-query 

[Source](https://groups.google.com/a/chromium.org/d/msg/net-dev/offElT1V6cM/XDLlL_5JBQAJ)

Edit: It's in the [wiki](https://github.com/pengelana/blocklist/wiki/DNS-over-HTTPS-(DoH)#chrome)

**Comment by pengelana** [comment]
Thanks
