### ISSUE TITLE
block scam website

### ISSUE THREAD

**Issue by Crukk11** [pengelana/blocklist#181]
http://bansosterbaru-2024.dieklick.com

https://app-kerajaan.qualityfn.com

![image](https://github.com/user-attachments/assets/afa92745-8cde-44e1-bcff-3b456076cb8d)
![image](https://github.com/user-attachments/assets/8414827b-c6bb-4e6a-b7b2-633d004b70f6)

**Comment by pengelana** [comment]
Done, Thanks!
