### ISSUE TITLE
Web Unair Not resolve

### ISSUE THREAD

**Issue by kclinsd** [pengelana/blocklist#195]
### Issue(s):

Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s): unair.ac.id

If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. 

- Domain(s): 

```

```

<hr>

### Detail:

- Your Issue Detail:

<hr>

<div align="center">
  <sub><a href="https://doh.tiar.app" target="_blank">Tiarap ⚡️</a></sub>
</div>

**Comment by pengelana** [comment]
Done, Thanks!
