### ISSUE TITLE
Tidak dapat mengakses postel.go.id dan subdomainnya postel.go.id *.postel.go.id 

### ISSUE THREAD

**Issue by zein3** [pengelana/blocklist#197]
### Issue(s):

Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Detail:

- Your Issue Detail:

Tidak dapat mengakses postel.go.id dan subdomainnya postel.go.id *.postel.go.id 

<hr>

<div align="center">
  <sub><a href="https://doh.tiar.app" target="_blank">Tiarap ⚡️</a></sub>
</div>

**Comment by pengelana** [comment]
`postel.go.id` tidak diblok oleh Tiarap.

~~~
$ drill @174.138.21.128 postel.go.id
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 60486
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; postel.go.id.        IN      A

;; ANSWER SECTION:
postel.go.id.   38353   IN      A       202.58.238.3

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 6 msec
;; SERVER: 174.138.21.128
;; WHEN: Tue Dec 17 11:04:42 2024
;; MSG SIZE  rcvd: 46
~~~
