### ISSUE TITLE
(request) energized list

### ISSUE THREAD

**Issue by 3xploiton3** [pengelana/blocklist#3]
Bro tambahkan list energized spark buat block ads, selalu update 
https://github.com/EnergizedProtection/block/blob/master/README.md#packs-1

**Comment by pengelana** [comment]
Energized sudah pernah di-include, terlalu banyak false positive.

**Comment by 3xploiton3** [comment]
Energized spark ga bro,
Klo keatasnya iya, saya sdh lama pakai ini di ublock, versi spark lebih
ramah ga seagressive basic apalagi ultimate

**Comment by pengelana** [comment]
Source dr Spark sudah semuanya di-include ke Tiarap, kalau ada perbedaan itu karena di-whitelist manual (false positive).

**Comment by pengelana** [comment]
Coba check ini https://github.com/notracking/hosts-blocklists.

**Comment by 3xploiton3** [comment]
Caranya lihat list whitelist manual dimana?

**Comment by pengelana** [comment]
Whitelistnya gak dipublish, ada di dalam script generator auto update.

**Comment by pengelana** [comment]
Domain yang diload ke Tiarap bisa dilihat disini: https://github.com/pengelana/blocklist/blob/master/domain.txt

Tiarap pakai wildcard jadi kalau domainnya terdaftar di domain.txt, semua subdomainnya juga diblok.

misalnya:

~~~
*.doubleclick.net
~~~

**Comment by 3xploiton3** [comment]
bro database dari domain.txt
ambil source dari mana saja?

kalau bisa di tambahkan di readme (link), biar orang lain tau dimana bisa menambahkan server ads yg harus diblock

**Comment by pengelana** [comment]
Sip, thanks!

source utamanya dari sini:
https://github.com/StevenBlack/hosts
https://github.com/notracking/hosts-blocklists
