### ISSUE TITLE
[bukan komplen] makasih

### ISSUE THREAD

**Issue by cubakcabak** [pengelana/blocklist#4]
mantap, tenkyu bro buat adblocking DoT sama DoH nya

sedikit saran, buat resolver nya pake cloudflare, dia anycast jadi siapa aja bisa lebih cepet konek ke server yang lebih deket secara geo routing

cloudflare baru aja nanam server di jakarta bro, lumayan lah ngurang2in latency

**Comment by pengelana** [comment]
Terima kasih sarannya.
