### ISSUE TITLE
Req Blocklist

### ISSUE THREAD

**Issue by rainazure** [pengelana/blocklist#40]
Apakah memungkinkan semacam pop up dari beberapa situs ini (muncul pada saat menggunakan provider indosat), diblock? 

jika bisa, maka berikut adalah alamatnya:

widget.mgid.com
ads.indosatooredoo.com
114.6.128.4:8004

Terima kasih.

**Comment by pengelana** [comment]
`widget.mgid.com` & `ads.indosatooredoo.com` domainnya sudah diblok.

114.6.128.4 tidak lewat dns.
