### ISSUE TITLE
godaddy.com is blocked, please whitelist

### ISSUE THREAD

**Issue by SScape** [pengelana/blocklist#47]
godaddy.com is blocked, please whitelist as it is not an ad or tracking site.

![image](https://user-images.githubusercontent.com/32894942/95447286-b2cfd080-098b-11eb-8ba1-9c2fd99f7343.png)

**Comment by pengelana** [comment]
Done, Thanks!

![Screen Shot 2020-10-08 at 11 48 04 PM](https://user-images.githubusercontent.com/787301/95483145-78812600-09c1-11eb-8287-6b4264984440.png)
