### ISSUE TITLE
(whitelist) safelinkconverter.com

### ISSUE THREAD

**Issue by 3xploiton3** [pengelana/blocklist#6]
tolong whitelist link ini
https://decrypt2.safelinkconverter.com

dari 
http://giga74.com/en/cost/www16.zippyshare.com?id=aHR0cHM6Ly93d3cxNi56X3BweXNoIXIpLmMobS92L2todHlqVkVRL2ZfbCkuaHRtbA==&c=1&user=18378#

**Comment by 3xploiton3** [comment]
whitlist tambahan
http://link.safelinkconverter.com

dari
https://gigapurbalingga.net/eset-nod32-antivirus-8-0-304-0-final-full-activation/

**Comment by pengelana** [comment]
kenapa harus diwhitelist?

**Comment by 3xploiton3** [comment]
Link itu semacam adf.ly
Short url

**Comment by pengelana** [comment]
done!
