### ISSUE TITLE
Whitelist: files.slack.com

### ISSUE THREAD

**Issue by ivokun** [pengelana/blocklist#67]
Hi, thanks for making this awesome service for free.

As I use Slack to communicate with my peers, could you whitelist `files.slack.com`?

**Comment by pengelana** [comment]
files.slack.com is not blocked.

**Comment by ivokun** [comment]
Fixed with auto-commit at:
https://github.com/pengelana/blocklist/commit/72d96af22bfd16b75c707d9a69e7e00da8941625#diff-9c95afa52d83734660f6352818b57dccc6226fabb32bb2c5b0e73d299e175a20L99348
