### ISSUE TITLE
(whitelist) olx

### ISSUE THREAD

**Issue by 3xploiton3** [pengelana/blocklist#7]
Saya gak tau host yg mana yg terblok

aplikasi olx tidak bisa térbuka menggunakan dot.tiar.app

Setelah saya ganti dns cloudflare baru bisa

**Comment by pengelana** [comment]
Baru download dari Apple app store, di ios tak ada masalah.

![index](https://user-images.githubusercontent.com/787301/64174298-91004200-ce8b-11e9-9284-25ee7b0d4043.jpg)

**Comment by pengelana** [comment]
yg diblok cuma tracking & location.

![index](https://user-images.githubusercontent.com/787301/64174755-81cdc400-ce8c-11e9-8fdf-d5220ca8cd99.jpg)

**Comment by pengelana** [comment]
Android bisa nih 
![index](https://user-images.githubusercontent.com/787301/64175077-25b76f80-ce8d-11e9-88af-decec9540116.jpg)

**Comment by 3xploiton3** [comment]
Waktu pertama kali download aplikasi, gak bisa di buka, harua register dan syaratnya harus mengaktifkan location permission

**Comment by pengelana** [comment]
coba lagi, sudah di-whitelist.

~~~

host -vt a location.olx.com 127.0.0.1


;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6044
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;location.olx.com.              IN      A

;; ANSWER SECTION:
location.olx.com.       513     IN      CNAME   olx.com.edgesuite.net.
olx.com.edgesuite.net.  3850    IN      CNAME   a1307.b.akamai.net.
a1307.b.akamai.net.     12      IN      A       173.222.148.43
a1307.b.akamai.net.     12      IN      A       173.222.148.35

~~~

**Comment by cebolang** [comment]
> Saya gak tau host yg mana yg terblok
> 
> aplikasi olx tidak bisa térbuka menggunakan dot.tiar.app
> 
> Setelah saya ganti dns cloudflare baru bisa

selama ini di iOS dan PC nggak masalah

**Comment by 3xploiton3** [comment]
> coba lagi, sudah di-whitelist.
> 
> ```
> 
> host -vt a location.olx.com 127.0.0.1
> 
> 
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6044
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;location.olx.com.              IN      A
> 
> ;; ANSWER SECTION:
> location.olx.com.       513     IN      CNAME   olx.com.edgesuite.net.
> olx.com.edgesuite.net.  3850    IN      CNAME   a1307.b.akamai.net.
> a1307.b.akamai.net.     12      IN      A       173.222.148.43
> a1307.b.akamai.net.     12      IN      A       173.222.148.35
> ```

terimakasih sudah berhasil 

case closed
