### ISSUE TITLE
Whitelist some servers

### ISSUE THREAD

**Issue by What-Zit-Tooya** [pengelana/blocklist#86]
Im using adguard for android and this DNS as upstream, pls whitelist these servers:
`www.googletagmanager.com` breaks antiadblock script inside adguard

`api-secure.solvemedia.com` can not resolve captcha on some websites

`zoover.adnetasia.com` `zoover.bannertrack.net` `yasni.bannertrack.net` and another  `adnetasia.com` `bannertrack.net` subdomains because its breakage anti-adblock script inside `nekopoi app`

**Comment by pengelana** [comment]
whitelist googletagmanager.com.
Thanks.

**Comment by What-Zit-Tooya** [comment]
@pengelana thank you,
these also need to be whitelisted:
`jsc.adskeeper.co.uk` 
`adskeeper.co.uk` it breaks anti adblock script on some website like this https://github.com/uBlockOrigin/uAssets/issues/9165#issuecomment-846555268
`yahoo.adnetasia.com` => breakage anti-adblock script on `nekopoi app`

**Comment by pengelana** [comment]
I will only allow googletagmanager.com.
The rest will block.

[adskeeper.co.uk](https://blog.malwarebytes.com/detections/adskeeper-co-uk/) identfied by malawarebytes as adware.

**Comment by What-Zit-Tooya** [comment]
> 
> 
> I will only allow googletagmanager.com.
> The rest will be block.

On my end, it's not whitelisted yet
