### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by indrapalijama** [pengelana/blocklist#88]
hi! been using DoH with iOS 14 profile, i noticed that for some sites (github, reddit) it doesn't want to connect, on github it's so slow and failed to load the images.
on reddit, it doesn't want to connect

**Comment by indrapalijama** [comment]
![image](https://user-images.githubusercontent.com/33986004/129184495-74ac9b65-17e5-432a-b4b2-e0b616c4bc6b.png)

**Comment by pengelana** [comment]
Most likely the profile is not active. After activated the DoH profile, restart iPhone.

Check with https://www.dnsleaktest.com/ to ensure that iPhone pointing to correct DNS.

![image](https://user-images.githubusercontent.com/787301/129292017-65d0d4b2-1a9f-4430-a7de-03099d5ea24d.png)
