### ISSUE TITLE
problem Adguardhome + quick protocol

### ISSUE THREAD

**Issue by Manssizz** [pengelana/blocklist#93]
i have issue with quic protocol, all protocol works well except quic
i've try Adguardhome quic protocol, it's work. but not for tiarap quic proto.  
![fio](https://user-images.githubusercontent.com/23637327/140497478-d6a366fb-f2ff-4fb9-834e-77c0eed76ef3.png)

**Comment by pengelana** [comment]
Please, use sdns stamps:

~~~ 
sdns://BAMAAAAAAAAAEjE3NC4xMzguMjkuMTc1Ojc4NAAMZG9oLnRpYXIuYXBw 
~~~

https://github.com/pengelana/blocklist/wiki/DNS-over-QUIC-(DoQ)
