### ISSUE TITLE
can't open site

### ISSUE THREAD

**Issue by Rh354** [pengelana/blocklist#97]
ga' bisa buka website teman-it.com. 
ketika di dig via dns telegram querynya mengarah ke teman-it.com IN A @174.138.21.128 jika tidak memakai doh.tiar.app ketika di dig mengarah ke 103.8.79.201 dan website bisa terbuka.

di tes via nebulo apps. juga mengarah ke 174.138.21.128, setelah di pointing manual di host ke 103.8.79.201 bisa

**Comment by pengelana** [comment]
Sila dicoba lagi, makasih.
