### ISSUE TITLE
Tidak bisa akses hiperdex

### ISSUE THREAD

**Issue by MohammadAdiyudha** [pengelana/blocklist#98]
Gatau kenapa tiar gabisa akses hiperdex.com

Tapi di dns lain bisa, ini web manga / manhwa / manhua, kalau bisa tolong di fix
![Screenshot_2021-12-04-05-07-47-398_com android chrome](https://user-images.githubusercontent.com/54175795/144679370-3586eb61-07a1-4b8e-b67b-d76572095e04.jpg)

**Comment by pengelana** [comment]
Done, thanks!
